//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_MessengerServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PTMessengerEntitiesModel : DbContext
    {
        public PTMessengerEntitiesModel()
            : base("name=PTMessengerEntitiesModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TLastLogin> TLastLogin { get; set; }
        public virtual DbSet<TUsers> TUsers { get; set; }
        public virtual DbSet<TMessage> TMessageSet { get; set; }
    }
}
