//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_MessengerServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLastLogin
    {
        public int TLastLogin_id { get; set; }
        public Nullable<int> TLastLogin_TUserID { get; set; }
        public byte[] TLastLogin_TS { get; set; }
        public string TLastLogin_UserIP { get; set; }
    
        public virtual TUsers TUsers { get; set; }
    }
}
