//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_MessengerServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUsers()
        {
            this.TLastLogin = new HashSet<TLastLogin>();
        }
    
        public int TUsers_id { get; set; }
        public string TUsers_login { get; set; }
        public string TUsers_email { get; set; }
        public string TUsers_passwd { get; set; }
        public string TUsers_desc { get; set; }
        public string TUser_imie { get; set; }
        public string TUser_nazwisko { get; set; }
        public string TUser_lock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TLastLogin> TLastLogin { get; set; }
    }
}
