//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_MessengerServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUsers
    {
        public int TUsers_id { get; set; }
        public string TUsers_login { get; set; }
        public string TUsers_email { get; set; }
        public string TUsers_passwd { get; set; }
        public string TUsers_desc { get; set; }
        public string TUser_imie { get; set; }
        public string TUser_nazwisko { get; set; }
        public bool TUser_lock { get; set; }
    }
}
